"""create voice_sessions table

Revision ID: 085afe4baffe
Revises: 99273c61a9de
Create Date: 2026-08-16 11:22:54.276843

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.rls import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "085afe4baffe"
down_revision: str | Sequence[str] | None = "99273c61a9de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voice_sessions",
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_voice_sessions_tenant_id"), "voice_sessions", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###

    # Manually added — not autogenerated. See docs/adr/0003 and migrations/rls.py.
    enable_rls("voice_sessions")


def downgrade() -> None:
    """Downgrade schema."""
    # Manually added — not autogenerated.
    disable_rls("voice_sessions")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_voice_sessions_tenant_id"), table_name="voice_sessions")
    op.drop_table("voice_sessions")
    # ### end Alembic commands ###
