"""add content_hash to documents

Revision ID: 188fb1a82a84
Revises: b91be877b219
Create Date: 2026-08-11 17:17:34.367417

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "188fb1a82a84"
down_revision: str | Sequence[str] | None = "b91be877b219"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("content_hash", sa.String(), nullable=True))
    op.create_index(op.f("ix_documents_content_hash"), "documents", ["content_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_content_hash"), table_name="documents")
    op.drop_column("documents", "content_hash")
    # ### end Alembic commands ###
