"""add conversation status column

Revision ID: 2bf340555aee
Revises: 385511a6264e
Create Date: 2026-08-15 18:06:51.065957

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2bf340555aee"
down_revision: str | Sequence[str] | None = "385511a6264e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand -- autogenerate's own bare
    # `nullable=False` fails against any pre-existing row (step 065's
    # own "default= only applies to new inserts, not existing rows"
    # lesson, e.g. is_email_verified/mfa_enabled's own migrations).
    op.add_column(
        "conversations",
        sa.Column("status", sa.String(), nullable=False, server_default="new"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "status")
    # ### end Alembic commands ###
