"""add conversation title and is_pinned columns

Revision ID: 3132d06dea6d
Revises: 38f8d61a1632
Create Date: 2026-08-15 19:04:58.206103

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3132d06dea6d"
down_revision: str | Sequence[str] | None = "38f8d61a1632"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("title", sa.String(), nullable=True))
    # server_default added by hand -- is_pinned is NOT NULL against any
    # pre-existing row (step 065's own "default= only applies to new
    # inserts" lesson); title needs no such default since it's nullable.
    op.add_column(
        "conversations",
        sa.Column("is_pinned", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "is_pinned")
    op.drop_column("conversations", "title")
    # ### end Alembic commands ###
