"""add embedding column and ivfflat index to chunks

Revision ID: 39e25a113a92
Revises: ae7205c04037
Create Date: 2026-08-14 16:17:42.248422

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39e25a113a92"
down_revision: str | Sequence[str] | None = "ae7205c04037"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Manually added — not autogenerated. docker-compose.yml's Postgres
    # image (pgvector/pgvector:pg16) and CI's service container both
    # bundle the extension, but neither installs it into the database
    # automatically — nothing in this repo has ever run `CREATE
    # EXTENSION vector` before, since this is the first column that
    # actually needs the type it provides.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chunks",
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    )
    op.create_index(
        "ix_chunks_embedding_ivfflat",
        "chunks",
        ["embedding"],
        unique=False,
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_chunks_embedding_ivfflat",
        table_name="chunks",
        postgresql_using="ivfflat",
        postgresql_with={"lists": 100},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_column("chunks", "embedding")
    # ### end Alembic commands ###
