"""create assistants table

Revision ID: 3ac10648782e
Revises: bf7dbf3962a5
Create Date: 2026-08-15 05:19:17.629713

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations.rls import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "3ac10648782e"
down_revision: str | Sequence[str] | None = "bf7dbf3962a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistants",
        sa.Column("knowledge_base_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("agent_configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["knowledge_base_id"], ["knowledge_bases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "knowledge_base_id", "slug", name="uq_assistants_knowledge_base_id_slug"
        ),
    )
    op.create_index(op.f("ix_assistants_tenant_id"), "assistants", ["tenant_id"], unique=False)
    # ### end Alembic commands ###

    # Manually added — not autogenerated. See docs/adr/0003 and migrations/rls.py.
    enable_rls("assistants")


def downgrade() -> None:
    """Downgrade schema."""
    # Manually added — not autogenerated.
    disable_rls("assistants")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assistants_tenant_id"), table_name="assistants")
    op.drop_table("assistants")
    # ### end Alembic commands ###
