"""add chunking strategy columns to documents

Revision ID: 443208c90b83
Revises: e73937d162b6
Create Date: 2026-08-14 13:30:17.121166

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "443208c90b83"
down_revision: str | Sequence[str] | None = "e73937d162b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("chunking_strategy", sa.String(), nullable=True))
    op.add_column("documents", sa.Column("chunking_strategy_source", sa.String(), nullable=True))
    op.add_column("documents", sa.Column("chunking_strategy_reasoning", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "chunking_strategy_reasoning")
    op.drop_column("documents", "chunking_strategy_source")
    op.drop_column("documents", "chunking_strategy")
    # ### end Alembic commands ###
