"""add user is_email_verified, create verification_tokens table

Revision ID: 69d534969a1c
Revises: df1c19c11aa8
Create Date: 2026-08-06 21:09:16.356195

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "69d534969a1c"
down_revision: str | Sequence[str] | None = "df1c19c11aa8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("purpose", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_tokens_purpose"), "verification_tokens", ["purpose"], unique=False
    )
    op.create_index(
        op.f("ix_verification_tokens_token_hash"),
        "verification_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_verification_tokens_user_id"), "verification_tokens", ["user_id"], unique=False
    )
    # server_default is required here, not just the ORM-level default=False
    # in models/user.py — this ALTER TABLE runs against a table that may
    # already have rows (e.g. the demo seed user), and a Python-side
    # default only applies to new inserts, not existing ones. Without it,
    # this fails with a NOT NULL violation on any non-empty users table —
    # caught by exactly that happening against the seeded dev database.
    op.add_column(
        "users",
        sa.Column("is_email_verified", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_email_verified")
    op.drop_index(op.f("ix_verification_tokens_user_id"), table_name="verification_tokens")
    op.drop_index(op.f("ix_verification_tokens_token_hash"), table_name="verification_tokens")
    op.drop_index(op.f("ix_verification_tokens_purpose"), table_name="verification_tokens")
    op.drop_table("verification_tokens")
    # ### end Alembic commands ###
