"""add expires_at to memories

Revision ID: 7378116256d3
Revises: b3a9f5eefcf9
Create Date: 2026-08-15 07:34:27.200444

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7378116256d3"
down_revision: str | Sequence[str] | None = "b3a9f5eefcf9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("memories", sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("memories", "expires_at")
    # ### end Alembic commands ###
