"""add voice_session_id to messages

Revision ID: 7aaec26c0dd2
Revises: 085afe4baffe
Create Date: 2026-08-16 16:09:09.808083

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7aaec26c0dd2"
down_revision: str | Sequence[str] | None = "085afe4baffe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("voice_session_id", sa.UUID(), nullable=True))
    # Named explicitly, not left as autogenerate's anonymous None -- this
    # project's Base.metadata has no naming_convention configured, so an
    # anonymous constraint has no name downgrade() could target to drop
    # it again (same fix f567d67cde4e's own memories.session_id FK
    # already needed).
    op.create_foreign_key(
        "fk_messages_voice_session_id_voice_sessions",
        "messages",
        "voice_sessions",
        ["voice_session_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_messages_voice_session_id_voice_sessions", "messages", type_="foreignkey"
    )
    op.drop_column("messages", "voice_session_id")
    # ### end Alembic commands ###
