"""create messages table

Revision ID: 8926d7ceef1e
Revises: f567d67cde4e
Create Date: 2026-08-15 09:42:33.215501

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.rls import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "8926d7ceef1e"
down_revision: str | Sequence[str] | None = "f567d67cde4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_tenant_id"), "messages", ["tenant_id"], unique=False)
    # ### end Alembic commands ###

    # Manually added — not autogenerated. See docs/adr/0003 and migrations/rls.py.
    enable_rls("messages")


def downgrade() -> None:
    """Downgrade schema."""
    # Manually added — not autogenerated.
    disable_rls("messages")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_tenant_id"), table_name="messages")
    op.drop_table("messages")
    # ### end Alembic commands ###
