"""add allowed_domains to security_settings

Revision ID: 99273c61a9de
Revises: 4effc7a3a36e
Create Date: 2026-08-16 03:13:59.639712

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "99273c61a9de"
down_revision: str | Sequence[str] | None = "4effc7a3a36e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default is required here, not just the ORM-level
    # default=list: every existing organization already has a
    # security_settings row (step 079's own migration), so a bare NOT
    # NULL ADD COLUMN would fail against that real data the same way
    # step 065's is_email_verified column did. Dropped immediately
    # after backfilling — new INSERTs get their default from the ORM
    # model instead, matching every other NOT-NULL-with-a-Python-
    # default column in this codebase.
    op.add_column(
        "security_settings",
        sa.Column(
            "allowed_domains",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.alter_column("security_settings", "allowed_domains", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("security_settings", "allowed_domains")
    # ### end Alembic commands ###
