"""create document_versions table

Revision ID: 9c8d8867b814
Revises: 39e25a113a92
Create Date: 2026-08-14 17:41:21.910680

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations.rls import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "9c8d8867b814"
down_revision: str | Sequence[str] | None = "39e25a113a92"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_versions",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("doc_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("extracted_text", sa.String(), nullable=True),
        sa.Column("content_hash", sa.String(), nullable=True),
        sa.Column("chunking_strategy", sa.String(), nullable=True),
        sa.Column("chunking_strategy_source", sa.String(), nullable=True),
        sa.Column("chunking_strategy_reasoning", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "document_id", "version_number", name="uq_document_versions_document_id_version"
        ),
    )
    op.create_index(
        op.f("ix_document_versions_document_id"), "document_versions", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_versions_tenant_id"), "document_versions", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###

    # Manually added — not autogenerated. See docs/adr/0003 and migrations/rls.py.
    enable_rls("document_versions")


def downgrade() -> None:
    """Downgrade schema."""
    # Manually added — not autogenerated.
    disable_rls("document_versions")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_versions_tenant_id"), table_name="document_versions")
    op.drop_index(op.f("ix_document_versions_document_id"), table_name="document_versions")
    op.drop_table("document_versions")
    # ### end Alembic commands ###
