"""create roles, permissions, role_permissions, memberships tables

Revision ID: a870af57e4d3
Revises: 9a7373a26668
Create Date: 2026-08-06 19:09:10.869570

"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.rls import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "a870af57e4d3"
down_revision: str | Sequence[str] | None = "9a7373a26668"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The built-in role catalog from AGENTS.md's role matrix, minus Platform
# Super Admin (that's User.is_platform_admin — see models/role.py).
BUILTIN_ROLES = [
    (
        "org_owner",
        "Organization Owner",
        "Full control over the organization, its billing, and all workspaces.",
    ),
    ("admin", "Administrator", "Manages users, settings, and workspaces within the organization."),
    ("manager", "Manager", "Manages a workspace's assistants, knowledge, and team."),
    ("knowledge_manager", "Knowledge Manager", "Manages knowledge bases and document ingestion."),
    ("developer", "Developer", "Manages API keys, integrations, and technical configuration."),
    ("support_agent", "Support Agent", "Handles conversations and customer interactions."),
    ("analyst", "Analyst", "Views analytics and reports; no configuration access."),
    ("viewer", "Viewer", "Read-only access to the organization's resources."),
    ("end_user", "End User", "A regular authenticated user interacting with assistants."),
    ("guest", "Guest", "Limited, temporary access."),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permissions_key"), "permissions", ["key"], unique=True)
    op.create_table(
        "roles",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "memberships",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_memberships_tenant_id"), "memberships", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_index(
        "uq_memberships_org_level",
        "memberships",
        ["tenant_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("workspace_id IS NULL"),
    )
    op.create_index(
        "uq_memberships_workspace_level",
        "memberships",
        ["tenant_id", "user_id", "workspace_id"],
        unique=True,
        postgresql_where=sa.text("workspace_id IS NOT NULL"),
    )
    # ### end Alembic commands ###

    # Manually added — not autogenerated.
    enable_rls("memberships")

    roles_table = sa.table(
        "roles",
        sa.column("id", sa.UUID()),
        sa.column("name", sa.String()),
        sa.column("display_name", sa.String()),
        sa.column("description", sa.String()),
    )
    op.bulk_insert(
        roles_table,
        [
            {
                "id": uuid.uuid4(),
                "name": name,
                "display_name": display_name,
                "description": description,
            }
            for name, display_name, description in BUILTIN_ROLES
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Manually added — not autogenerated.
    disable_rls("memberships")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_memberships_workspace_level",
        table_name="memberships",
        postgresql_where=sa.text("workspace_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_memberships_org_level",
        table_name="memberships",
        postgresql_where=sa.text("workspace_id IS NULL"),
    )
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_tenant_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_key"), table_name="permissions")
    op.drop_table("permissions")
    # ### end Alembic commands ###
