"""add message feedback_type column

Revision ID: ab703b266981
Revises: f51b86ffcb71
Create Date: 2026-08-15 20:35:12.519377

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab703b266981"
down_revision: str | Sequence[str] | None = "f51b86ffcb71"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("feedback_type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "feedback_type")
    # ### end Alembic commands ###
