"""add assistant is_public column

Revision ID: b103046e3fef
Revises: ab703b266981
Create Date: 2026-08-15 21:51:15.872296

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b103046e3fef"
down_revision: str | Sequence[str] | None = "ab703b266981"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand -- NOT NULL against any pre-existing
    # row (step 065's own "default= only applies to new inserts" lesson).
    op.add_column(
        "assistants",
        sa.Column("is_public", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistants", "is_public")
    # ### end Alembic commands ###
