"""add importance score to memories

Revision ID: b3a9f5eefcf9
Revises: 67bf87ea4557
Create Date: 2026-08-15 06:39:36.163206

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3a9f5eefcf9"
down_revision: str | Sequence[str] | None = "67bf87ea4557"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("memories", sa.Column("importance_score", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("memories", "importance_score")
    # ### end Alembic commands ###
