"""add extracted_text to documents

Revision ID: b91be877b219
Revises: b13e46412c00
Create Date: 2026-08-10 17:14:31.585428

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b91be877b219"
down_revision: str | Sequence[str] | None = "b13e46412c00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("extracted_text", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "extracted_text")
    # ### end Alembic commands ###
