"""create security_settings table

Revision ID: c02f16e313e1
Revises: 6be477156324
Create Date: 2026-08-08 19:27:30.702906

"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.rls import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "c02f16e313e1"
down_revision: str | Sequence[str] | None = "6be477156324"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "security_settings",
        sa.Column("session_timeout_minutes", sa.Integer(), nullable=True),
        sa.Column("password_min_length", sa.Integer(), nullable=True),
        sa.Column("password_require_uppercase", sa.Boolean(), nullable=False),
        sa.Column("password_require_number", sa.Boolean(), nullable=False),
        sa.Column("password_require_symbol", sa.Boolean(), nullable=False),
        sa.Column("mfa_required", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", name="uq_security_settings_tenant_id"),
    )
    op.create_index(
        op.f("ix_security_settings_tenant_id"), "security_settings", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###

    # Manually added — not autogenerated. See docs/adr/0003 and migrations/rls.py.
    enable_rls("security_settings")

    # Backfill: every organization that already exists needs its one row
    # too, same reasoning as any NOT NULL column added against seeded
    # data (step 065's is_email_verified) — routers/organization.py's
    # auto-create on create_organization only covers organizations
    # created AFTER this migration. UUIDs generated in Python, same
    # pattern as 1d0ef14faf9e's permission-catalog seed, since this runs
    # as a raw INSERT, not through the ORM.
    connection = op.get_bind()
    organization_ids = [
        row.id for row in connection.execute(sa.text("SELECT id FROM organizations")).fetchall()
    ]
    if organization_ids:
        security_settings_table = sa.table(
            "security_settings",
            sa.column("id", sa.UUID()),
            sa.column("tenant_id", sa.UUID()),
            sa.column("password_require_uppercase", sa.Boolean()),
            sa.column("password_require_number", sa.Boolean()),
            sa.column("password_require_symbol", sa.Boolean()),
            sa.column("mfa_required", sa.Boolean()),
        )
        op.bulk_insert(
            security_settings_table,
            [
                {
                    "id": uuid.uuid4(),
                    "tenant_id": org_id,
                    "password_require_uppercase": False,
                    "password_require_number": False,
                    "password_require_symbol": False,
                    "mfa_required": False,
                }
                for org_id in organization_ids
            ],
        )


def downgrade() -> None:
    """Downgrade schema."""
    # Manually added — not autogenerated.
    disable_rls("security_settings")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_security_settings_tenant_id"), table_name="security_settings")
    op.drop_table("security_settings")
    # ### end Alembic commands ###
