"""create agent_execution_logs table

Revision ID: e91a4c6f0b32
Revises: b6e1f4a087cd
Create Date: 2026-08-17 08:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.rls import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "e91a4c6f0b32"
down_revision: str | Sequence[str] | None = "b6e1f4a087cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "agent_execution_logs",
        sa.Column("agent_name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_execution_logs_agent_name"), "agent_execution_logs", ["agent_name"]
    )
    op.create_index(
        op.f("ix_agent_execution_logs_tenant_id"), "agent_execution_logs", ["tenant_id"]
    )

    # Manually added — not autogenerated. See docs/adr/0003 and migrations/rls.py.
    enable_rls("agent_execution_logs")


def downgrade() -> None:
    """Downgrade schema."""
    # Manually added — not autogenerated.
    disable_rls("agent_execution_logs")

    op.drop_index(op.f("ix_agent_execution_logs_tenant_id"), table_name="agent_execution_logs")
    op.drop_index(op.f("ix_agent_execution_logs_agent_name"), table_name="agent_execution_logs")
    op.drop_table("agent_execution_logs")
