"""add storage fields to documents

Revision ID: f3a9fe0bb607
Revises: 242396798236
Create Date: 2026-08-09 00:14:17.678035

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3a9fe0bb607"
down_revision: str | Sequence[str] | None = "242396798236"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("storage_key", sa.String(), nullable=False))
    op.add_column("documents", sa.Column("content_type", sa.String(), nullable=False))
    op.add_column("documents", sa.Column("size_bytes", sa.Integer(), nullable=False))
    # Named explicitly -- no naming_convention is configured on Base's
    # MetaData, so leaving this auto-named (None) would let Postgres pick
    # something ad hoc that downgrade()'s drop_constraint couldn't
    # reliably target back.
    op.create_unique_constraint("uq_documents_storage_key", "documents", ["storage_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_documents_storage_key", "documents", type_="unique")
    op.drop_column("documents", "size_bytes")
    op.drop_column("documents", "content_type")
    op.drop_column("documents", "storage_key")
    # ### end Alembic commands ###
