"""add message citations column

Revision ID: f51b86ffcb71
Revises: c9d46e1de36d
Create Date: 2026-08-15 19:55:21.396209

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f51b86ffcb71"
down_revision: str | Sequence[str] | None = "c9d46e1de36d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand -- NOT NULL against any pre-existing
    # row (step 065's own "default= only applies to new inserts" lesson).
    op.add_column(
        "messages",
        sa.Column(
            "citations",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="[]",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "citations")
    # ### end Alembic commands ###
