"""create conversations table and link memory session_id

Revision ID: f567d67cde4e
Revises: 7378116256d3
Create Date: 2026-08-15 09:14:20.992407

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from migrations.rls import disable_rls, enable_rls

# revision identifiers, used by Alembic.
revision: str = "f567d67cde4e"
down_revision: str | Sequence[str] | None = "7378116256d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("assistant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["assistant_id"], ["assistants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversations_tenant_id"), "conversations", ["tenant_id"], unique=False
    )
    # Defensive cleanup, not autogenerated: memories.session_id has been an
    # unconstrained UUID since step 162 (models/memory.py's own docstring),
    # so any pre-existing row's session_id is not guaranteed to reference a
    # real conversation -- this table is brand new and starts empty, so
    # every non-null session_id at this point is by definition orphaned. A
    # session-scoped memory with no real session is meaningless (scope
    # exists to distinguish it from a user/organization-scoped row), so
    # dropping the row rather than nulling session_id keeps scope and
    # session_id consistent with each other.
    op.execute(
        "DELETE FROM memories WHERE session_id IS NOT NULL "
        "AND session_id NOT IN (SELECT id FROM conversations)"
    )
    # Named explicitly, not left as autogenerate's anonymous None -- this
    # project's Base.metadata has no naming_convention configured, so an
    # anonymous constraint has no name downgrade() could target to drop
    # it again.
    op.create_foreign_key(
        "fk_memories_session_id_conversations",
        "memories",
        "conversations",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###

    # Manually added — not autogenerated. See docs/adr/0003 and migrations/rls.py.
    enable_rls("conversations")


def downgrade() -> None:
    """Downgrade schema."""
    # Manually added — not autogenerated.
    disable_rls("conversations")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_memories_session_id_conversations", "memories", type_="foreignkey")
    op.drop_index(op.f("ix_conversations_tenant_id"), table_name="conversations")
    op.drop_table("conversations")
    # ### end Alembic commands ###
